spring:
  cloud:
    gateway:
      routes:
        - id: spring-6-rest-mvc
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/*
#      httpserver:
#        wiretap: true
#      httpclient:
#        wiretap: true
#logging:
#  level:
#    root: error
#    reactor.netty: trace
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: trace